substitutions:
  _IMAGE_TAG: "n/a"
  _BUILD_TARGET: website

steps:
  # Download image to cache from
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - "docker pull gcr.io/$PROJECT_ID/worker:latest || exit 0"

  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--cache-from=gcr.io/$PROJECT_ID/${_BUILD_TARGET}:latest"
      - "--target=${_BUILD_TARGET}"
      - "--tag=gcr.io/$PROJECT_ID/${_BUILD_TARGET}:${_IMAGE_TAG}"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "tag"
      - "gcr.io/$PROJECT_ID/${_BUILD_TARGET}:${_IMAGE_TAG}"
      - "gcr.io/$PROJECT_ID/${_BUILD_TARGET}:latest"

images:
  - "gcr.io/$PROJECT_ID/${_BUILD_TARGET}:${_IMAGE_TAG}"
  - "gcr.io/$PROJECT_ID/${_BUILD_TARGET}:latest"
