"""fulfillment_status from enum => string

Revision ID: 2d15cb59b42d
Revises: bf4a8c07f792
Create Date: 2023-03-28 08:26:23.917619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2d15cb59b42d"
down_revision = "bf4a8c07f792"
branch_labels = None
depends_on = None


def upgrade():
    # jscpd:ignore-start
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "annual_membership",
        "fulfillment_status",
        existing_type=postgresql.ENUM(
            "PENDING", "FULFILLED", "CANCELED", name="fulfillment_status_enum"
        ),
        type_=sa.String(length=32),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
    # jscpd:ignore-end
    sql = 'REASSIGN OWNED BY current_user TO "read_write"'
    op.execute(sql)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "annual_membership",
        "fulfillment_status",
        existing_type=sa.String(length=32),
        type_=postgresql.ENUM(
            "PENDING", "FULFILLED", "CANCELED", name="fulfillment_status_enum"
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
