"""Users! Now with Slack!

Revision ID: 4de69c4e6736
Revises: b3f07657bc30
Create Date: 2023-03-01 13:50:19.715508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4de69c4e6736"
down_revision = "b3f07657bc30"
branch_labels = None
depends_on = None


def upgrade():
    # jscpd:ignore-start
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slack_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slack_id", sa.String(), nullable=True),
        sa.Column("team_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("real_name", sa.String(), nullable=True),
        sa.Column("tz", sa.String(), nullable=True),
        sa.Column("tz_label", sa.String(), nullable=True),
        sa.Column("tz_offset", sa.String(), nullable=True),
        sa.Column("profile", sa.String(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column("is_primary_owner", sa.Boolean(), nullable=False),
        sa.Column("is_restricted", sa.Boolean(), nullable=False),
        sa.Column("is_ultra_restricted", sa.Boolean(), nullable=False),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column("updated", sa.String(), nullable=True),
        sa.Column("is_app_user", sa.Boolean(), nullable=False),
        sa.Column("has_2fa", sa.Boolean(), nullable=False),
        sa.Column("is_workflow_bot", sa.Boolean(), nullable=False),
        sa.Column("is_invited_user", sa.Boolean(), nullable=False),
        sa.Column("is_email_confirmed", sa.Boolean(), nullable=False),
        sa.Column("who_can_share_contact_card", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    # jscpd:ignore-end
    sql = 'REASSIGN OWNED BY current_user TO "read_write"'
    op.execute(sql)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("slack_user")
    # ### end Alembic commands ###
