"""Add SquarespaceWebhook

Revision ID: 97e73b85f5c4
Revises: d2901c482e8b
Create Date: 2022-02-16 15:10:04.373154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "97e73b85f5c4"
down_revision = "d2901c482e8b"
branch_labels = None
depends_on = None


def upgrade():
    # jscpd:ignore-start
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "squarespace_webhook",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("webhook_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=True),
        sa.Column("website_id", sa.String(), nullable=True),
        sa.Column("endpoint_url", sa.String(), nullable=True),
        sa.Column("topics", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("secret", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", "webhook_id"),
    )
    # ### end Alembic commands ###
    # jscpd:ignore-end
    sql = "REASSIGN OWNED BY current_user TO 'read_write'"
    op.execute(sql)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("squarespace_webhook")
    # ### end Alembic commands ###
