"""Slack Users! Now with emails!

Revision ID: bf4a8c07f792
Revises: 4de69c4e6736
Create Date: 2023-03-02 13:16:07.379505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bf4a8c07f792"
down_revision = "4de69c4e6736"
branch_labels = None
depends_on = None


def upgrade():
    # jscpd:ignore-start
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("slack_user", sa.Column("email", sa.String(), nullable=True))
    # ### end Alembic commands ###
    # jscpd:ignore-end
    sql = 'REASSIGN OWNED BY current_user TO "read_write"'
    op.execute(sql)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slack_user", "email")
    # ### end Alembic commands ###
