"""Bigcommerce tables and such

Revision ID: daad72fa8c6e
Revises: c79375ac1f51
Create Date: 2023-02-22 11:04:00.710381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "daad72fa8c6e"
down_revision = "c79375ac1f51"
branch_labels = None
depends_on = None


def upgrade():
    # jscpd:ignore-start
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_hash", sa.String(length=16), nullable=False),
        sa.Column("access_token", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_hash"),
    )
    op.create_table(
        "store_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("users", sa.Column("bigcommerce_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    # jscpd:ignore-end
    sql = 'REASSIGN OWNED BY current_user TO "read_write"'
    op.execute(sql)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "bigcommerce_id")
    op.drop_table("store_user")
    op.drop_table("store")
    # ### end Alembic commands ###
